### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Benjamin-Dobell** [feross/ieee754#10]
Any chance we could get a sane license on this?

`package.json` (NPM) claims this is an MIT library, but the [LICENSE](https://github.com/feross/ieee754/blob/master/LICENSE) file says otherwise. It's actually a mish-mash of MIT, 3-clause BSD and a custom footnote. To be clear it's not "dual licensed" as MIT and BSD, it's somehow both at once (with modifications from Brian!)

Could you please contact the original license holders and request the removal of the footnote, then relicense your portion as 3-clause BSD, then there will be just one license for this code.

**Comment by Benjamin-Dobell** [comment]
Also the README says "Romain Beauxis" is a copyright holder but the LICENSE file again says otherwise.

**Comment by feross** [comment]
Fixed in 1.1.7.

**Comment by Benjamin-Dobell** [comment]
@feross Awesome! But did you mean to schedule this for `1.1.7` rather than close the issue? Or is `1.1.7` already available somewhere?

**Comment by Benjamin-Dobell** [comment]
Oh, you commented before pushing...

Errr, so ah, have you completely rewritten since the original license? Or did you request this be allowed by the previous license holders?

The license file not being "simple" isn't really the issue, it's the correctness that I'm concerned about.

EDIT: When I say "it's the correctness that I'm concerned about.", I really mean "I'd like to use this library without committing copyright infringement."

**Comment by feross** [comment]
I'm not a lawyer. You'll have to make that call for yourself.

If you want to contact the author of the original fork and investigate further, feel free. I'm happy to use whatever license or copyright line would make him/her happy, as long as it remains under an open source license.

**Comment by Benjamin-Dobell** [comment]
Oh wow! _Please_ revert!

Without the original license holder's permission the change you just made is clear cut copyright infringement and there's Git history to prove it. Worse still users of this library will now unknowingly be committing copyright infringement!

If you can't legally change the license then the appropriate thing to do is revert, then update `package.json` to _not_ say "MIT" but instead say "SEE LICENSE IN LICENSE" (as per NPM instructions).

**Comment by feross** [comment]
Using the original license seems the most legally-sound. Fixed in 1.1.8.

**Comment by Benjamin-Dobell** [comment]
@feross Sorry for all the fuss!

I'm building a license screen for a client and stumbled across this and it had me a bit stumped. Thanks for sorting it out quickly.

**Comment by feross** [comment]
Sure thing.
