### ISSUE TITLE
Mantissa <-> Byte length always paired?

### ISSUE THREAD

**Issue by elidoran** [feross/ieee754#14]
The functions allow specifying the mantissa and the byte length.

When playing around it seems they are always paired like (23, 4) and (52, 8).

Do you know if the mantissa is always tied to the byte length like that?
Or, is there a time when we'd vary the mantissa for some reason?

Thank you

**Comment by feross** [comment]
I'm actually not really an expert on this stuff. FWIW, in the [buffer](https://github.com/feross/buffer) module, I only ever call this library with (23, 4) and (52, 8).

**Comment by Borewit** [comment]
I think the _mantissa_ or _fraction_ width can be derived from the float precision in bytes, as this is standardized in  IEEE 754:

| Precision                                                                                | bits | bytes | exponent width | fraction width |
|------------------------------------------------------------------------------------------|-----:|------:|---------------:|---------------:|
| [half-precision](https://en.wikipedia.org/wiki/Half-precision_floating-point_format)     |   16 |     2 |              5 |             10 |
| [single-precision](https://en.wikipedia.org/wiki/Single-precision)                       |   32 |     4 |              8 |             23 |
| [double-precision](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) |   64 |     8 |             23 |             52 |
| [extended-precision](https://en.wikipedia.org/wiki/Extended_precision)                   |   80 |    10 |             15 |             63 |

Working on [token-types#55](https://github.com/Borewit/token-types/issues/55) I came across this one.
