### ISSUE TITLE
ESM build?

### ISSUE THREAD

**Issue by xtuc** [feross/ieee754#24]
Hi @feross,

I forked your library here: https://github.com/feross/ieee754/compare/master...xtuc:master and I was wondering if that's something that could be merged upstream?

Basically, the source is now an ECMAScript Module and uses a Babel to transpile it down to CJS before publishing on npm.

**Comment by feross** [comment]
Thanks for your concern, but this accomplishes nothing. It just adds more dependencies and lines of code to maintain to the repo. Once ESM is natively supported in Node.js, I would be willing to consider this. But in the meantime, I'm not willing to add tons of extra tooling for no reason.
