### ISSUE TITLE
Where do the number 24 and 77 come from?

### ISSUE THREAD

**Issue by JaysonHwang** [feross/ieee754#35]
Where do the number -24 and -77 come from? They are just like magic code to me.Though I have already learned knowledge about ieee754, i stuck here. Can you explain why it work here or give some tips about it?  thanks a lot. @feross 

https://github.com/feross/ieee754/blob/master/index.js#L48

**Comment by feross** [comment]
I wish I could help, but this isn't a support forum. I'm closing this issue since there's no bug to fix here. If someone else would like to answer, feel free :)
